# Generated by Django 5.0 on 2024-01-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='username',
        ),
    ]
