# Generated by Django 4.2.9 on 2024-01-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_rename_body_post_description_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(max_length=250),
        ),
    ]
