# Generated by Django 4.2.9 on 2024-01-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_video_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='post',
            new_name='post_id',
        ),
    ]
