# Generated by Django 4.2.9 on 2024-01-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
