# Generated by Django 4.2.9 on 2024-01-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_video_url_delete_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='preview',
            new_name='images',
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
