# Generated by Django 5.0 on 2024-01-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_rename_owner_comment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='description',
        ),
    ]
