# Generated by Django 5.0 on 2024-01-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='username',
            new_name='user',
        ),
    ]
